@startuml diagram

interface IEnvSensDrv
{
    + {abstract} return_code init()

    + {abstract} return_code startContinuousMeasurements()
    + {abstract} return_code startSingleMeasurement()
    + {abstract} return_code stopMeasuring()

    + {abstract} return_code readTemperature(int32_t &temperature)
    + {abstract} return_code readHumidity(uint32_t &humidity)
    + {abstract} return_code readPressure(uint32_t &pressure)

    + {abstract} return_code getMeasurementState()
    + {abstract} void process()

    + {abstract} ~IEnvSensDrv()
}

class EnvSensBME280Drv implements IEnvSensDrv
{
    -i2c_master_bus_handle_t m_bus_handle
    -i2c_master_dev_handle_t m_dev_handle

    -bme280_config_t m_bme280_config
    -bme280_calib_data m_calib_data

    -return_code m_state

    -int32_t m_temperature
    -uint32_t m_pressure
    -uint32_t m_humidity

    +EnvSensBME280Drv(bme280_config_t *bme280_config, i2c_master_bus_handle_t bus_handle)

    +return_code init()

    +return_code startContinuousMeasurements()
    +return_code startSingleMeasurement()
    +return_code stopMeasuring()

    +return_code readTemperature(int32_t &temperature)
    +return_code readHumidity(uint32_t &humidity)
    +return_code readPressure(uint32_t &pressure)

    +return_code getMeasurementState()
    +void process()

    +~EnvSensBME280Drv()
}

class EnvSensBMP280Drv implements IEnvSensDrv
{
    -i2c_master_bus_handle_t m_bus_handle
    -i2c_master_dev_handle_t m_dev_handle

    -bmp280_config_t m_bmp280_config
    -bmp280_calib_data m_calib_data

    -return_code m_state

    -int32_t m_temperature
    -uint32_t m_pressure

    +EnvSensBMP280Drv(bmp280_config_t *bmp280_config, i2c_master_bus_handle_t bus_handle)

    +return_code init()

    +return_code startContinuousMeasurements()
    +return_code startSingleMeasurement()
    +return_code stopMeasuring()

    +return_code readTemperature(int32_t &temperature)
    +return_code readPressure(uint32_t &pressure)

    +return_code getMeasurementState()
    +void process()

    +~EnvSensBMP280Drv()
}

@enduml