#define CONFIG_EXAMPLE_CONNECT_WIFI true
#define CONFIG_EXAMPLE_WIFI_SSID "SA52_S"
#define CONFIG_EXAMPLE_WIFI_PASSWORD "nokia123"
#define EXAMPLE_WIFI_SCAN_METHOD 1
#define EXAMPLE_WIFI_CONNECT_AP_SORT_METHOD 1
#define EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD 4
#define CONFIG_EXAMPLE_WIFI_CONN_MAX_RETRY 6
#define CONFIG_EXAMPLE_WIFI_SCAN_RSSI_THRESHOLD -127